### ISSUE TITLE
部分讀音與您商討。

### ISSUE THREAD

**Issue by DerFahrgast** [yiranlll/pieng-yo-hua#1]
下面列出了一些我的淺薄認知，或許並不正確，共同探討。

> 下文所指「白讀/老派」，區別在於有無固定詞語留存。

|字|音|層次|註|
| ------- | ------ | -------- |---|
|騾|lei|白讀|見於「騾子」。|
|費|xi|白讀|見於「費電」等。|
|肥|xi|白讀|見於「腳肥」等。|
|義|ni|白讀|見於「義道」等。|
|杵|su|白讀|見於「石杵」，舊時打地基用具。|
|鬼|jyu|白讀|見於「毛鬼神」，一種小鬼，常作詈語。|
|塵|zheng|白讀|見於「承塵」，舊時木構房屋天花板。|
|緯|yu|白讀|見於「緯線」，織布用語。|
|尾|yi|白讀|見於「尾巴」「二尾子」等。|
|甑|zei|白讀|見於「籠甑甑」，蒸籠。|
|車|she|白讀|見於「扇車」，一種農具。|
|淘|do|白讀|見於「超淘」，（與週邊縣市比對，應並非「朝道」二字）。|
|揣|cae|白讀|見於「揣到懷懷兒」等。|
|睫|zaq|白讀|見於「眼睫毛」。|
|澀|shaq|白讀|見於「澀巴巴底」等，形容水果等口感發澀。|
|色|shaq|白讀|見於「色兒」，骰子；又「黑/白/綠色色的」等。|
|赤|shaq|白讀|見於「赤㞘子」「赤拍腳」等。|
|射|shaq|白讀|見於「射出去啦」（參考《 “一头拾来” 的 “拾” 本字为 “射” 考》）。|
|摔|suaq|白讀|見於「摔打」，打；又「木摔」，舊時一種打地基用具|
|曹|zo|白讀|見於地名「曹村」。|
|弓|jyueng|白讀|見於地名「弓村」。|
|永|yu|白讀|見於地名「永城」。|
|營|yi|白讀|見於地名「南/北營」等。|
|郭|gaq|白讀|見於地名「東/西郭村」。|
|琉|niou|白讀|見於地名「琉璃廟」，「琉璃圪嘣」「琉璃蛋」舊時亦如此。|
|文|meng|白讀|僅見於地名「文祠神」，舊有晉文公祠。|
|崖|nie|白讀|見於地名「紅崖底/西崖窯」等。|
|邢|xi|白讀|見於地名「邢村」，80年代改名爲「喜村」。|
|魏|yu|白讀|見於地名「魏樂」。|
|蒲|bu|白讀|見於地名「達蒲」。|
|屯|dueng|白讀|見於地名「陶屯」。|
|祠|si|白讀|見於地名「東/西源祠」「晉祠」等。|
|塗|du|老派|如「圪塗上幾副隊子」。|
|鞏|jyueng|老派|中老年鞏姓仍如此稱呼。|
|裴|bae|老派|老年裴姓仍如此稱呼。|
|圍|yu|老派|老派會說「周圓yu上一圈土」。|
|率|suaq|老派|舊時「率領」即如此音。|
|詞|si|老派||
|歲|xyu|老派||
|捕|pu|老派||
|醫|ni|老派||
|彥/諺|niang|老派||
|甫|pu|老派||
|卻|qiaq|老派||
|確|qiaq|老派||
|菊|qyuaq|老派||
|掬|qyuaq|老派||
|鞠|qyuaq|老派||
|疆|qiang|舊文讀|舊時如此稱「新疆」。|
|超|sho|舊文讀|白讀音爲cho。舊文讀見於南部山脈稱呼「超山」，白讀見於「超淘」。受普通話影響，舊文讀被新文讀cho取代， 恰好與白讀音一致。|
|波|po|舊文讀||
|腌|yaq|兩讀|yaq見於「腌鹹菜」。似可對應影葉三開 iep，或影業三開 iap。|
|掛|kua|兩讀|kua見於「掛幌子」「掛洋刀」等等。|
|秦|ceng|存疑|見於說書中人名「秦瓊」，或爲舊文讀。介休有地名「秦/tsəŋ/樹」。|
|榆|nyu|存疑|見於舊時稱呼「榆次」。|
|疝|suon|存疑|見於「疝氣」。|
|撫|wu|存疑|僅見於老派「撫養」一詞，其中養爲文讀。|
|眠|mieng|存疑|見於老派「睡眠」一詞。|
|冒|mu|存疑|暫僅汾陽可做旁證，故存疑。見於「冒地說」、「冒寫」，未經準備地做某事。|
|吸|qiaq|存疑|見於「把水吸干」等。|
|樗|qyu|存疑|見於「樗股股樹」，臭椿。|
|緒|xyu||「緒」讀suei似爲侯先生誤錄，段村如此讀，但城內或無此音。|
|齫|kueng||似爲「啃」讀kueng的本字。|
|淊|ngang||似爲「淹」讀ngang的本字，爲二等字。影嚴三開 qiam 的類推或待商榷。|

平遙梗攝二等開白讀較混亂。兄字表內，以下字與城內白讀似略有出入。西村較爲統一，均爲ia；城內、東南爲[ie/i]、ia不等。
|    字     |     音   |      註    |
| ------- | ------ | -------- |
|迸|bie|見於「迸炒花」「迸開綻綻」等。|
|繃|bie|見於「繃被子」，縫。|
|棚|bie|見於「棚棚」。|
|坑|qie|見於地名「干坑」(非本村人多將「朱坑」「干坑」讀作kang)。「朱坑」讀如qiaq，似爲增生喉塞。|
|猛|mia|見於「發猛財」「猛不防」等。|
|萌|mia|暫僅介休可做旁證，故存疑。見於「細萌兒兒」等，形容纖弱瘦小。|
|澎|pia|存疑。見於「澎下一地」等。|

**Comment by yiranlll** [comment]
感谢，已照作修改。

另：

- 由「骡」想到「螺」似乎常读lei，一并录入
- 「射」shaq之前已因为类推录入了，歪打正着
- 「眠」似乎是读半边，不过既有就应当录入
- yi/ni、yu/nyu目前看来较混乱不好整理，之后可能会按模糊音处理
